package com.bits.bdfp.inventory.demandorder

/**
 * Created by prianka.adhikary on 9/9/2015.
 */

public enum DemandOrderStatus {
    NOT_SUBMITTED, PROCESSING, CANCELED, MERGED, REJECTED, DELIVERED, UNDER_REVIEW, ORDER_BOOKED, PROCESSED, UNDER_PROCESS, APPROVED, WAITING_FOR_APPROVAL, READY_FOR_SHIPMENT, SENT_FOR_PROCESSING, IN_TRANSIT
}