package com.docu.plugin.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2015-05-13T18:37:11.709+06:00
 * Generated source version: 2.4.2
 * 
 */
@WebServiceClient(name = "CommonPluginWebServiceWSDL", 
                  wsdlLocation = "http://10.100.18.112:9191/syncclient/services/commonPluginWeb?wsdl",
                  targetNamespace = "http://cxfws.docu.com/") 
public class CommonPluginWebServiceWSDL extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cxfws.docu.com/", "CommonPluginWebServiceWSDL");
    public final static QName CommonPluginWebServicePort = new QName("http://cxfws.docu.com/", "CommonPluginWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.100.18.112:9191/syncclient/services/commonPluginWeb?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CommonPluginWebServiceWSDL.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.100.18.112:9191/syncclient/services/commonPluginWeb?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CommonPluginWebServiceWSDL(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CommonPluginWebServiceWSDL(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommonPluginWebServiceWSDL() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CommonPluginWebServiceWSDL(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CommonPluginWebServiceWSDL(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CommonPluginWebServiceWSDL(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ICommonPluginWebServiceWSDL
     */
    @WebEndpoint(name = "CommonPluginWebServicePort")
    public ICommonPluginWebServiceWSDL getCommonPluginWebServicePort() {
        return super.getPort(CommonPluginWebServicePort, ICommonPluginWebServiceWSDL.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICommonPluginWebServiceWSDL
     */
    @WebEndpoint(name = "CommonPluginWebServicePort")
    public ICommonPluginWebServiceWSDL getCommonPluginWebServicePort(WebServiceFeature... features) {
        return super.getPort(CommonPluginWebServicePort, ICommonPluginWebServiceWSDL.class, features);
    }

}
