package com.docu.plugin.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2015-05-13T18:37:11.649+06:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://com.docu", name = "ICommonPluginWebServiceWSDL")
@XmlSeeAlso({ObjectFactory.class})
public interface ICommonPluginWebServiceWSDL {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteCity", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteCity")
    @WebMethod
    @ResponseWrapper(localName = "deleteCityResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteCityResponse")
    public boolean deleteCity(
        @WebParam(name = "cityDto", targetNamespace = "")
        com.docu.plugin.wsdl.CityDTO cityDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveLanguage", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveLanguage")
    @WebMethod
    @ResponseWrapper(localName = "saveLanguageResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveLanguageResponse")
    public boolean saveLanguage(
        @WebParam(name = "languageDto", targetNamespace = "")
        com.docu.plugin.wsdl.LanguageDTO languageDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveBloodGroup", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveBloodGroup")
    @WebMethod
    @ResponseWrapper(localName = "saveBloodGroupResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveBloodGroupResponse")
    public boolean saveBloodGroup(
        @WebParam(name = "bloodGroupDto", targetNamespace = "")
        com.docu.plugin.wsdl.BloodGroupDTO bloodGroupDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteGlobalHeadOffice", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteGlobalHeadOffice")
    @WebMethod
    @ResponseWrapper(localName = "deleteGlobalHeadOfficeResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteGlobalHeadOfficeResponse")
    public boolean deleteGlobalHeadOffice(
        @WebParam(name = "globalHeadOfficeDto", targetNamespace = "")
        com.docu.plugin.wsdl.GlobalHeadOfficeDTO globalHeadOfficeDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deletePhysicalOfficeInfo", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeletePhysicalOfficeInfo")
    @WebMethod
    @ResponseWrapper(localName = "deletePhysicalOfficeInfoResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeletePhysicalOfficeInfoResponse")
    public boolean deletePhysicalOfficeInfo(
        @WebParam(name = "physicalOfficeInfoDto", targetNamespace = "")
        com.docu.plugin.wsdl.PhysicalOfficeInfoDTO physicalOfficeInfoDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveOrganizationDepartment", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveOrganizationDepartment")
    @WebMethod
    @ResponseWrapper(localName = "saveOrganizationDepartmentResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveOrganizationDepartmentResponse")
    public boolean saveOrganizationDepartment(
        @WebParam(name = "organizationDepartmentDto", targetNamespace = "")
        com.docu.plugin.wsdl.OrganizationDepartmentDTO organizationDepartmentDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveCity", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveCity")
    @WebMethod
    @ResponseWrapper(localName = "saveCityResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveCityResponse")
    public boolean saveCity(
        @WebParam(name = "cityDto", targetNamespace = "")
        com.docu.plugin.wsdl.CityDTO cityDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteDashboardPortlet", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteDashboardPortlet")
    @WebMethod
    @ResponseWrapper(localName = "deleteDashboardPortletResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteDashboardPortletResponse")
    public boolean deleteDashboardPortlet(
        @WebParam(name = "dashboardPortletDto", targetNamespace = "")
        com.docu.plugin.wsdl.DashboardPortletDTO dashboardPortletDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveHobby", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveHobby")
    @WebMethod
    @ResponseWrapper(localName = "saveHobbyResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveHobbyResponse")
    public boolean saveHobby(
        @WebParam(name = "hobbyDto", targetNamespace = "")
        com.docu.plugin.wsdl.HobbyDTO hobbyDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveUserAuthority", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveUserAuthority")
    @WebMethod
    @ResponseWrapper(localName = "saveUserAuthorityResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveUserAuthorityResponse")
    public boolean saveUserAuthority(
        @WebParam(name = "authorityDto", targetNamespace = "")
        com.docu.plugin.wsdl.UserAuthorityDTO authorityDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteMeasurementUnit", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteMeasurementUnit")
    @WebMethod
    @ResponseWrapper(localName = "deleteMeasurementUnitResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteMeasurementUnitResponse")
    public boolean deleteMeasurementUnit(
        @WebParam(name = "measurementUnitDto", targetNamespace = "")
        com.docu.plugin.wsdl.MeasurementUnitDTO measurementUnitDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveContinent", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveContinent")
    @WebMethod
    @ResponseWrapper(localName = "saveContinentResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveContinentResponse")
    public boolean saveContinent(
        @WebParam(name = "continentDto", targetNamespace = "")
        com.docu.plugin.wsdl.ContinentDTO continentDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveUserPreference", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveUserPreference")
    @WebMethod
    @ResponseWrapper(localName = "saveUserPreferenceResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveUserPreferenceResponse")
    public boolean saveUserPreference(
        @WebParam(name = "userPreferenceDTO", targetNamespace = "")
        com.docu.plugin.wsdl.UserPreferenceDTO userPreferenceDTO
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveCountryLevelEntityOffice", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveCountryLevelEntityOffice")
    @WebMethod
    @ResponseWrapper(localName = "saveCountryLevelEntityOfficeResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveCountryLevelEntityOfficeResponse")
    public boolean saveCountryLevelEntityOffice(
        @WebParam(name = "countryLevelEntityOfficeDto", targetNamespace = "")
        com.docu.plugin.wsdl.CountryLevelEntityOfficeDTO countryLevelEntityOfficeDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteGender", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteGender")
    @WebMethod
    @ResponseWrapper(localName = "deleteGenderResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteGenderResponse")
    public boolean deleteGender(
        @WebParam(name = "genderDto", targetNamespace = "")
        com.docu.plugin.wsdl.GenderDTO genderDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteApplicationUserAuthority", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteApplicationUserAuthority")
    @WebMethod
    @ResponseWrapper(localName = "deleteApplicationUserAuthorityResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteApplicationUserAuthorityResponse")
    public boolean deleteApplicationUserAuthority(
        @WebParam(name = "applicationUserAuthorityDto", targetNamespace = "")
        com.docu.plugin.wsdl.ApplicationUserAuthorityDTO applicationUserAuthorityDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveOfficeCategoryMapping", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveOfficeCategoryMapping")
    @WebMethod
    @ResponseWrapper(localName = "saveOfficeCategoryMappingResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveOfficeCategoryMappingResponse")
    public boolean saveOfficeCategoryMapping(
        @WebParam(name = "officeCategoryMappingDto", targetNamespace = "")
        com.docu.plugin.wsdl.OfficeCategoryMappingDTO officeCategoryMappingDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveCountryOfficeHierarchy", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveCountryOfficeHierarchy")
    @WebMethod
    @ResponseWrapper(localName = "saveCountryOfficeHierarchyResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveCountryOfficeHierarchyResponse")
    public boolean saveCountryOfficeHierarchy(
        @WebParam(name = "countryOfficeHierarchyDto", targetNamespace = "")
        com.docu.plugin.wsdl.CountryOfficeHierarchyDTO countryOfficeHierarchyDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteFrequency", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteFrequency")
    @WebMethod
    @ResponseWrapper(localName = "deleteFrequencyResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteFrequencyResponse")
    public boolean deleteFrequency(
        @WebParam(name = "frequencyDto", targetNamespace = "")
        com.docu.plugin.wsdl.FrequencyDTO frequencyDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteAddressType", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteAddressType")
    @WebMethod
    @ResponseWrapper(localName = "deleteAddressTypeResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteAddressTypeResponse")
    public boolean deleteAddressType(
        @WebParam(name = "addressTypeDto", targetNamespace = "")
        com.docu.plugin.wsdl.AddressTypeDTO addressTypeDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveGlobalHeadOffice", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveGlobalHeadOffice")
    @WebMethod
    @ResponseWrapper(localName = "saveGlobalHeadOfficeResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveGlobalHeadOfficeResponse")
    public boolean saveGlobalHeadOffice(
        @WebParam(name = "globalHeadOfficeDto", targetNamespace = "")
        com.docu.plugin.wsdl.GlobalHeadOfficeDTO globalHeadOfficeDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveMeasurementUnit", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveMeasurementUnit")
    @WebMethod
    @ResponseWrapper(localName = "saveMeasurementUnitResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveMeasurementUnitResponse")
    public boolean saveMeasurementUnit(
        @WebParam(name = "measurementUnitDto", targetNamespace = "")
        com.docu.plugin.wsdl.MeasurementUnitDTO measurementUnitDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteHobby", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteHobby")
    @WebMethod
    @ResponseWrapper(localName = "deleteHobbyResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteHobbyResponse")
    public boolean deleteHobby(
        @WebParam(name = "hobbyDto", targetNamespace = "")
        com.docu.plugin.wsdl.HobbyDTO hobbyDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteNationalityType", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteNationalityType")
    @WebMethod
    @ResponseWrapper(localName = "deleteNationalityTypeResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteNationalityTypeResponse")
    public boolean deleteNationalityType(
        @WebParam(name = "nationalityTypeDto", targetNamespace = "")
        com.docu.plugin.wsdl.NationalityTypeDTO nationalityTypeDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteApplicationConfig", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteApplicationConfig")
    @WebMethod
    @ResponseWrapper(localName = "deleteApplicationConfigResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteApplicationConfigResponse")
    public boolean deleteApplicationConfig(
        @WebParam(name = "applicationConfigDto", targetNamespace = "")
        com.docu.plugin.wsdl.ApplicationConfigDTO applicationConfigDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "savePhysicalOfficeInfo", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SavePhysicalOfficeInfo")
    @WebMethod
    @ResponseWrapper(localName = "savePhysicalOfficeInfoResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SavePhysicalOfficeInfoResponse")
    public boolean savePhysicalOfficeInfo(
        @WebParam(name = "physicalOfficeInfoDto", targetNamespace = "")
        com.docu.plugin.wsdl.PhysicalOfficeInfoDTO physicalOfficeInfoDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteMediaType", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteMediaType")
    @WebMethod
    @ResponseWrapper(localName = "deleteMediaTypeResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteMediaTypeResponse")
    public boolean deleteMediaType(
        @WebParam(name = "mediaTypeDto", targetNamespace = "")
        com.docu.plugin.wsdl.MediaTypeDTO mediaTypeDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveSourceOfFund", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveSourceOfFund")
    @WebMethod
    @ResponseWrapper(localName = "saveSourceOfFundResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveSourceOfFundResponse")
    public boolean saveSourceOfFund(
        @WebParam(name = "sourceOfFundDto", targetNamespace = "")
        com.docu.plugin.wsdl.SourceOfFundDTO sourceOfFundDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveOfficeInfo", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveOfficeInfo")
    @WebMethod
    @ResponseWrapper(localName = "saveOfficeInfoResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveOfficeInfoResponse")
    public boolean saveOfficeInfo(
        @WebParam(name = "officeInfoDto", targetNamespace = "")
        com.docu.plugin.wsdl.OfficeInfoDTO officeInfoDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteWorkingDay", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteWorkingDay")
    @WebMethod
    @ResponseWrapper(localName = "deleteWorkingDayResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteWorkingDayResponse")
    public boolean deleteWorkingDay(
        @WebParam(name = "workingDayDto", targetNamespace = "")
        com.docu.plugin.wsdl.WorkingDayDTO workingDayDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteMaritalStatus", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteMaritalStatus")
    @WebMethod
    @ResponseWrapper(localName = "deleteMaritalStatusResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteMaritalStatusResponse")
    public boolean deleteMaritalStatus(
        @WebParam(name = "maritalStatusDto", targetNamespace = "")
        com.docu.plugin.wsdl.MaritalStatusDTO maritalStatusDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteReligion", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteReligion")
    @WebMethod
    @ResponseWrapper(localName = "deleteReligionResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteReligionResponse")
    public boolean deleteReligion(
        @WebParam(name = "religionDto", targetNamespace = "")
        com.docu.plugin.wsdl.ReligionDTO religionDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteOrganization", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteOrganization")
    @WebMethod
    @ResponseWrapper(localName = "deleteOrganizationResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteOrganizationResponse")
    public boolean deleteOrganization(
        @WebParam(name = "organizationDto", targetNamespace = "")
        com.docu.plugin.wsdl.OrganizationDTO organizationDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveHolidayType", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveHolidayType")
    @WebMethod
    @ResponseWrapper(localName = "saveHolidayTypeResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveHolidayTypeResponse")
    public boolean saveHolidayType(
        @WebParam(name = "holidayTypeDto", targetNamespace = "")
        com.docu.plugin.wsdl.HolidayTypeDTO holidayTypeDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveHoldingCompanyOffice", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveHoldingCompanyOffice")
    @WebMethod
    @ResponseWrapper(localName = "saveHoldingCompanyOfficeResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveHoldingCompanyOfficeResponse")
    public boolean saveHoldingCompanyOffice(
        @WebParam(name = "holdingCompanyOfficeDto", targetNamespace = "")
        com.docu.plugin.wsdl.HoldingCompanyOfficeDTO holdingCompanyOfficeDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteModeOfPayment", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteModeOfPayment")
    @WebMethod
    @ResponseWrapper(localName = "deleteModeOfPaymentResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteModeOfPaymentResponse")
    public boolean deleteModeOfPayment(
        @WebParam(name = "modeOfPaymentDto", targetNamespace = "")
        com.docu.plugin.wsdl.ModeOfPaymentDTO modeOfPaymentDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteApplicationUserAndDependencies", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteApplicationUserAndDependencies")
    @WebMethod
    @ResponseWrapper(localName = "deleteApplicationUserAndDependenciesResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteApplicationUserAndDependenciesResponse")
    public boolean deleteApplicationUserAndDependencies(
        @WebParam(name = "applicationUserAndDependenciesDTO", targetNamespace = "")
        com.docu.plugin.wsdl.ApplicationUserAndDependenciesDTO applicationUserAndDependenciesDTO
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveOccupation", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveOccupation")
    @WebMethod
    @ResponseWrapper(localName = "saveOccupationResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveOccupationResponse")
    public boolean saveOccupation(
        @WebParam(name = "occupationDto", targetNamespace = "")
        com.docu.plugin.wsdl.OccupationDTO occupationDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveIdentificationDocumentType", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveIdentificationDocumentType")
    @WebMethod
    @ResponseWrapper(localName = "saveIdentificationDocumentTypeResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveIdentificationDocumentTypeResponse")
    public boolean saveIdentificationDocumentType(
        @WebParam(name = "identificationDocumentTypeDto", targetNamespace = "")
        com.docu.plugin.wsdl.IdentificationDocumentTypeDTO identificationDocumentTypeDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteHoliday", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteHoliday")
    @WebMethod
    @ResponseWrapper(localName = "deleteHolidayResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteHolidayResponse")
    public boolean deleteHoliday(
        @WebParam(name = "holidayDto", targetNamespace = "")
        com.docu.plugin.wsdl.HolidayDTO holidayDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteHoldingCompanyOffice", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteHoldingCompanyOffice")
    @WebMethod
    @ResponseWrapper(localName = "deleteHoldingCompanyOfficeResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteHoldingCompanyOfficeResponse")
    public boolean deleteHoldingCompanyOffice(
        @WebParam(name = "holdingCompanyOfficeDto", targetNamespace = "")
        com.docu.plugin.wsdl.HoldingCompanyOfficeDTO holdingCompanyOfficeDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteAuthorityDashboardMapping", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteAuthorityDashboardMapping")
    @WebMethod
    @ResponseWrapper(localName = "deleteAuthorityDashboardMappingResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteAuthorityDashboardMappingResponse")
    public boolean deleteAuthorityDashboardMapping(
        @WebParam(name = "authorityDashboardMappingDto", targetNamespace = "")
        com.docu.plugin.wsdl.AuthorityDashboardMappingDTO authorityDashboardMappingDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "resetApplicationUser", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.ResetApplicationUser")
    @WebMethod
    @ResponseWrapper(localName = "resetApplicationUserResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.ResetApplicationUserResponse")
    public boolean resetApplicationUser(
        @WebParam(name = "applicationUserDto", targetNamespace = "")
        com.docu.plugin.wsdl.ApplicationUserDTO applicationUserDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteOfficeCategory", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteOfficeCategory")
    @WebMethod
    @ResponseWrapper(localName = "deleteOfficeCategoryResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteOfficeCategoryResponse")
    public boolean deleteOfficeCategory(
        @WebParam(name = "officeCategoryDto", targetNamespace = "")
        com.docu.plugin.wsdl.OfficeCategoryDTO officeCategoryDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveModeOfPayment", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveModeOfPayment")
    @WebMethod
    @ResponseWrapper(localName = "saveModeOfPaymentResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveModeOfPaymentResponse")
    public boolean saveModeOfPayment(
        @WebParam(name = "modeOfPaymentDto", targetNamespace = "")
        com.docu.plugin.wsdl.ModeOfPaymentDTO modeOfPaymentDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveGender", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveGender")
    @WebMethod
    @ResponseWrapper(localName = "saveGenderResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveGenderResponse")
    public boolean saveGender(
        @WebParam(name = "genderDto", targetNamespace = "")
        com.docu.plugin.wsdl.GenderDTO genderDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveApplicationUserAndDependencies", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveApplicationUserAndDependencies")
    @WebMethod
    @ResponseWrapper(localName = "saveApplicationUserAndDependenciesResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveApplicationUserAndDependenciesResponse")
    public boolean saveApplicationUserAndDependencies(
        @WebParam(name = "applicationUserAndDependenciesDTO", targetNamespace = "")
        com.docu.plugin.wsdl.ApplicationUserAndDependenciesDTO applicationUserAndDependenciesDTO
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteOfficeType", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteOfficeType")
    @WebMethod
    @ResponseWrapper(localName = "deleteOfficeTypeResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteOfficeTypeResponse")
    public boolean deleteOfficeType(
        @WebParam(name = "officeTypeDto", targetNamespace = "")
        com.docu.plugin.wsdl.OfficeTypeDTO officeTypeDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveOfficeAddress", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveOfficeAddress")
    @WebMethod
    @ResponseWrapper(localName = "saveOfficeAddressResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveOfficeAddressResponse")
    public boolean saveOfficeAddress(
        @WebParam(name = "officeAddressDto", targetNamespace = "")
        com.docu.plugin.wsdl.OfficeAddressDTO officeAddressDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveApplicationUserAuthority", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveApplicationUserAuthority")
    @WebMethod
    @ResponseWrapper(localName = "saveApplicationUserAuthorityResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveApplicationUserAuthorityResponse")
    public boolean saveApplicationUserAuthority(
        @WebParam(name = "applicationUserAuthorityDto", targetNamespace = "")
        com.docu.plugin.wsdl.ApplicationUserAuthorityDTO applicationUserAuthorityDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteEmailNotification", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteEmailNotification")
    @WebMethod
    @ResponseWrapper(localName = "deleteEmailNotificationResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteEmailNotificationResponse")
    public boolean deleteEmailNotification(
        @WebParam(name = "emailNotificationDto", targetNamespace = "")
        com.docu.plugin.wsdl.EmailNotificationDTO emailNotificationDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveOfficeType", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveOfficeType")
    @WebMethod
    @ResponseWrapper(localName = "saveOfficeTypeResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveOfficeTypeResponse")
    public boolean saveOfficeType(
        @WebParam(name = "officeTypeDto", targetNamespace = "")
        com.docu.plugin.wsdl.OfficeTypeDTO officeTypeDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveCodeGenerationRule", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveCodeGenerationRule")
    @WebMethod
    @ResponseWrapper(localName = "saveCodeGenerationRuleResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveCodeGenerationRuleResponse")
    public boolean saveCodeGenerationRule(
        @WebParam(name = "codeGenerationRuleDto", targetNamespace = "")
        com.docu.plugin.wsdl.CodeGenerationRuleDTO codeGenerationRuleDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveSalutation", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveSalutation")
    @WebMethod
    @ResponseWrapper(localName = "saveSalutationResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveSalutationResponse")
    public boolean saveSalutation(
        @WebParam(name = "salutationDto", targetNamespace = "")
        com.docu.plugin.wsdl.SalutationDTO salutationDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteSalutation", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteSalutation")
    @WebMethod
    @ResponseWrapper(localName = "deleteSalutationResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteSalutationResponse")
    public boolean deleteSalutation(
        @WebParam(name = "salutationDto", targetNamespace = "")
        com.docu.plugin.wsdl.SalutationDTO salutationDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteCountryOfficeHierarchy", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteCountryOfficeHierarchy")
    @WebMethod
    @ResponseWrapper(localName = "deleteCountryOfficeHierarchyResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteCountryOfficeHierarchyResponse")
    public boolean deleteCountryOfficeHierarchy(
        @WebParam(name = "countryOfficeHierarchyDto", targetNamespace = "")
        com.docu.plugin.wsdl.CountryOfficeHierarchyDTO countryOfficeHierarchyDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteOfficeCategoryMapping", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteOfficeCategoryMapping")
    @WebMethod
    @ResponseWrapper(localName = "deleteOfficeCategoryMappingResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteOfficeCategoryMappingResponse")
    public boolean deleteOfficeCategoryMapping(
        @WebParam(name = "officeCategoryMappingDto", targetNamespace = "")
        com.docu.plugin.wsdl.OfficeCategoryMappingDTO officeCategoryMappingDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveCountryHeadOffice", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveCountryHeadOffice")
    @WebMethod
    @ResponseWrapper(localName = "saveCountryHeadOfficeResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveCountryHeadOfficeResponse")
    public boolean saveCountryHeadOffice(
        @WebParam(name = "countryHeadOfficeDto", targetNamespace = "")
        com.docu.plugin.wsdl.CountryHeadOfficeDTO countryHeadOfficeDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveUserPortletPreference", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveUserPortletPreference")
    @WebMethod
    @ResponseWrapper(localName = "saveUserPortletPreferenceResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveUserPortletPreferenceResponse")
    public boolean saveUserPortletPreference(
        @WebParam(name = "userPortletPreferenceDTO", targetNamespace = "")
        com.docu.plugin.wsdl.UserPortletPreferenceDTO userPortletPreferenceDTO
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteBankAccountType", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteBankAccountType")
    @WebMethod
    @ResponseWrapper(localName = "deleteBankAccountTypeResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteBankAccountTypeResponse")
    public boolean deleteBankAccountType(
        @WebParam(name = "bankAccountTypeDto", targetNamespace = "")
        com.docu.plugin.wsdl.BankAccountTypeDTO bankAccountTypeDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteCountry", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteCountry")
    @WebMethod
    @ResponseWrapper(localName = "deleteCountryResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteCountryResponse")
    public boolean deleteCountry(
        @WebParam(name = "countryDto", targetNamespace = "")
        com.docu.plugin.wsdl.CountryDTO countryDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteLanguage", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteLanguage")
    @WebMethod
    @ResponseWrapper(localName = "deleteLanguageResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteLanguageResponse")
    public boolean deleteLanguage(
        @WebParam(name = "languageDto", targetNamespace = "")
        com.docu.plugin.wsdl.LanguageDTO languageDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveSecurityQuestion", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveSecurityQuestion")
    @WebMethod
    @ResponseWrapper(localName = "saveSecurityQuestionResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveSecurityQuestionResponse")
    public boolean saveSecurityQuestion(
        @WebParam(name = "securityQuestionDto", targetNamespace = "")
        com.docu.plugin.wsdl.SecurityQuestionDTO securityQuestionDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveAuthorityDashboardMapping", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveAuthorityDashboardMapping")
    @WebMethod
    @ResponseWrapper(localName = "saveAuthorityDashboardMappingResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveAuthorityDashboardMappingResponse")
    public boolean saveAuthorityDashboardMapping(
        @WebParam(name = "authorityDashboardMappingDto", targetNamespace = "")
        com.docu.plugin.wsdl.AuthorityDashboardMappingDTO authorityDashboardMappingDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveMailNotificationInfo", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveMailNotificationInfo")
    @WebMethod
    @ResponseWrapper(localName = "saveMailNotificationInfoResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveMailNotificationInfoResponse")
    public boolean saveMailNotificationInfo(
        @WebParam(name = "mailNotificationInfoDto", targetNamespace = "")
        com.docu.plugin.wsdl.MailNotificationInfoDTO mailNotificationInfoDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteSecurityQuestion", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteSecurityQuestion")
    @WebMethod
    @ResponseWrapper(localName = "deleteSecurityQuestionResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteSecurityQuestionResponse")
    public boolean deleteSecurityQuestion(
        @WebParam(name = "securityQuestionDto", targetNamespace = "")
        com.docu.plugin.wsdl.SecurityQuestionDTO securityQuestionDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteUserAuthority", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteUserAuthority")
    @WebMethod
    @ResponseWrapper(localName = "deleteUserAuthorityResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteUserAuthorityResponse")
    public boolean deleteUserAuthority(
        @WebParam(name = "authorityDto", targetNamespace = "")
        com.docu.plugin.wsdl.UserAuthorityDTO authorityDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteTaskStatus", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteTaskStatus")
    @WebMethod
    @ResponseWrapper(localName = "deleteTaskStatusResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteTaskStatusResponse")
    public boolean deleteTaskStatus(
        @WebParam(name = "taskStatusDto", targetNamespace = "")
        com.docu.plugin.wsdl.TaskStatusDTO taskStatusDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveHoliday", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveHoliday")
    @WebMethod
    @ResponseWrapper(localName = "saveHolidayResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveHolidayResponse")
    public boolean saveHoliday(
        @WebParam(name = "holidayDto", targetNamespace = "")
        com.docu.plugin.wsdl.HolidayDTO holidayDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteCountryHeadOffice", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteCountryHeadOffice")
    @WebMethod
    @ResponseWrapper(localName = "deleteCountryHeadOfficeResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteCountryHeadOfficeResponse")
    public boolean deleteCountryHeadOffice(
        @WebParam(name = "countryHeadOfficeDto", targetNamespace = "")
        com.docu.plugin.wsdl.CountryHeadOfficeDTO countryHeadOfficeDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteContinent", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteContinent")
    @WebMethod
    @ResponseWrapper(localName = "deleteContinentResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteContinentResponse")
    public boolean deleteContinent(
        @WebParam(name = "continentDto", targetNamespace = "")
        com.docu.plugin.wsdl.ContinentDTO continentDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveOfficeCategory", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveOfficeCategory")
    @WebMethod
    @ResponseWrapper(localName = "saveOfficeCategoryResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveOfficeCategoryResponse")
    public boolean saveOfficeCategory(
        @WebParam(name = "officeCategoryDto", targetNamespace = "")
        com.docu.plugin.wsdl.OfficeCategoryDTO officeCategoryDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteIdentificationDocumentType", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteIdentificationDocumentType")
    @WebMethod
    @ResponseWrapper(localName = "deleteIdentificationDocumentTypeResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteIdentificationDocumentTypeResponse")
    public boolean deleteIdentificationDocumentType(
        @WebParam(name = "identificationDocumentTypeDto", targetNamespace = "")
        com.docu.plugin.wsdl.IdentificationDocumentTypeDTO identificationDocumentTypeDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveCommonAddressInfo", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveCommonAddressInfo")
    @WebMethod
    @ResponseWrapper(localName = "saveCommonAddressInfoResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveCommonAddressInfoResponse")
    public boolean saveCommonAddressInfo(
        @WebParam(name = "commonAddressInfoDto", targetNamespace = "")
        com.docu.plugin.wsdl.CommonAddressInfoDTO commonAddressInfoDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveOrganization", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveOrganization")
    @WebMethod
    @ResponseWrapper(localName = "saveOrganizationResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveOrganizationResponse")
    public boolean saveOrganization(
        @WebParam(name = "organizationDto", targetNamespace = "")
        com.docu.plugin.wsdl.OrganizationDTO organizationDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveAddressType", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveAddressType")
    @WebMethod
    @ResponseWrapper(localName = "saveAddressTypeResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveAddressTypeResponse")
    public boolean saveAddressType(
        @WebParam(name = "addressTypeDto", targetNamespace = "")
        com.docu.plugin.wsdl.AddressTypeDTO addressTypeDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveDashboardPortlet", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveDashboardPortlet")
    @WebMethod
    @ResponseWrapper(localName = "saveDashboardPortletResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveDashboardPortletResponse")
    public boolean saveDashboardPortlet(
        @WebParam(name = "dashboardPortletDto", targetNamespace = "")
        com.docu.plugin.wsdl.DashboardPortletDTO dashboardPortletDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveMediaType", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveMediaType")
    @WebMethod
    @ResponseWrapper(localName = "saveMediaTypeResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveMediaTypeResponse")
    public boolean saveMediaType(
        @WebParam(name = "mediaTypeDto", targetNamespace = "")
        com.docu.plugin.wsdl.MediaTypeDTO mediaTypeDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteOfficeAddress", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteOfficeAddress")
    @WebMethod
    @ResponseWrapper(localName = "deleteOfficeAddressResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteOfficeAddressResponse")
    public boolean deleteOfficeAddress(
        @WebParam(name = "officeAddressDto", targetNamespace = "")
        com.docu.plugin.wsdl.OfficeAddressDTO officeAddressDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveReligion", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveReligion")
    @WebMethod
    @ResponseWrapper(localName = "saveReligionResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveReligionResponse")
    public boolean saveReligion(
        @WebParam(name = "religionDto", targetNamespace = "")
        com.docu.plugin.wsdl.ReligionDTO religionDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteOccupation", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteOccupation")
    @WebMethod
    @ResponseWrapper(localName = "deleteOccupationResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteOccupationResponse")
    public boolean deleteOccupation(
        @WebParam(name = "occupationDto", targetNamespace = "")
        com.docu.plugin.wsdl.OccupationDTO occupationDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveApplicationConfig", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveApplicationConfig")
    @WebMethod
    @ResponseWrapper(localName = "saveApplicationConfigResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveApplicationConfigResponse")
    public boolean saveApplicationConfig(
        @WebParam(name = "applicationConfigDto", targetNamespace = "")
        com.docu.plugin.wsdl.ApplicationConfigDTO applicationConfigDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteBloodGroup", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteBloodGroup")
    @WebMethod
    @ResponseWrapper(localName = "deleteBloodGroupResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteBloodGroupResponse")
    public boolean deleteBloodGroup(
        @WebParam(name = "bloodGroupDto", targetNamespace = "")
        com.docu.plugin.wsdl.BloodGroupDTO bloodGroupDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveMaritalStatus", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveMaritalStatus")
    @WebMethod
    @ResponseWrapper(localName = "saveMaritalStatusResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveMaritalStatusResponse")
    public boolean saveMaritalStatus(
        @WebParam(name = "maritalStatusDto", targetNamespace = "")
        com.docu.plugin.wsdl.MaritalStatusDTO maritalStatusDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveUserFavoriteLink", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveUserFavoriteLink")
    @WebMethod
    @ResponseWrapper(localName = "saveUserFavoriteLinkResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveUserFavoriteLinkResponse")
    public boolean saveUserFavoriteLink(
        @WebParam(name = "userFavoriteLinkDto", targetNamespace = "")
        com.docu.plugin.wsdl.UserFavoriteLinkDTO userFavoriteLinkDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteExamination", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteExamination")
    @WebMethod
    @ResponseWrapper(localName = "deleteExaminationResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteExaminationResponse")
    public boolean deleteExamination(
        @WebParam(name = "examinationDto", targetNamespace = "")
        com.docu.plugin.wsdl.ExaminationDTO examinationDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveEmailNotification", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveEmailNotification")
    @WebMethod
    @ResponseWrapper(localName = "saveEmailNotificationResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveEmailNotificationResponse")
    public boolean saveEmailNotification(
        @WebParam(name = "emailNotificationDto", targetNamespace = "")
        com.docu.plugin.wsdl.EmailNotificationDTO emailNotificationDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteOfficeInfo", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteOfficeInfo")
    @WebMethod
    @ResponseWrapper(localName = "deleteOfficeInfoResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteOfficeInfoResponse")
    public boolean deleteOfficeInfo(
        @WebParam(name = "officeInfoDto", targetNamespace = "")
        com.docu.plugin.wsdl.OfficeInfoDTO officeInfoDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteSourceOfFund", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteSourceOfFund")
    @WebMethod
    @ResponseWrapper(localName = "deleteSourceOfFundResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteSourceOfFundResponse")
    public boolean deleteSourceOfFund(
        @WebParam(name = "sourceOfFundDto", targetNamespace = "")
        com.docu.plugin.wsdl.SourceOfFundDTO sourceOfFundDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveWorkingDay", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveWorkingDay")
    @WebMethod
    @ResponseWrapper(localName = "saveWorkingDayResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveWorkingDayResponse")
    public boolean saveWorkingDay(
        @WebParam(name = "workingDayDto", targetNamespace = "")
        com.docu.plugin.wsdl.WorkingDayDTO workingDayDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteApplicationUser", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteApplicationUser")
    @WebMethod
    @ResponseWrapper(localName = "deleteApplicationUserResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteApplicationUserResponse")
    public boolean deleteApplicationUser(
        @WebParam(name = "applicationUserDto", targetNamespace = "")
        com.docu.plugin.wsdl.ApplicationUserDTO applicationUserDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveExamination", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveExamination")
    @WebMethod
    @ResponseWrapper(localName = "saveExaminationResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveExaminationResponse")
    public boolean saveExamination(
        @WebParam(name = "examinationDto", targetNamespace = "")
        com.docu.plugin.wsdl.ExaminationDTO examinationDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteRelationship", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteRelationship")
    @WebMethod
    @ResponseWrapper(localName = "deleteRelationshipResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteRelationshipResponse")
    public boolean deleteRelationship(
        @WebParam(name = "relationshipDto", targetNamespace = "")
        com.docu.plugin.wsdl.RelationshipDTO relationshipDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteUserFavoriteLink", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteUserFavoriteLink")
    @WebMethod
    @ResponseWrapper(localName = "deleteUserFavoriteLinkResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteUserFavoriteLinkResponse")
    public boolean deleteUserFavoriteLink(
        @WebParam(name = "userFavoriteLinkDto", targetNamespace = "")
        com.docu.plugin.wsdl.UserFavoriteLinkDTO userFavoriteLinkDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteCommonAddressInfo", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteCommonAddressInfo")
    @WebMethod
    @ResponseWrapper(localName = "deleteCommonAddressInfoResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteCommonAddressInfoResponse")
    public boolean deleteCommonAddressInfo(
        @WebParam(name = "commonAddressInfoDto", targetNamespace = "")
        com.docu.plugin.wsdl.CommonAddressInfoDTO commonAddressInfoDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveRelationship", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveRelationship")
    @WebMethod
    @ResponseWrapper(localName = "saveRelationshipResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveRelationshipResponse")
    public boolean saveRelationship(
        @WebParam(name = "relationshipDto", targetNamespace = "")
        com.docu.plugin.wsdl.RelationshipDTO relationshipDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteCodeGenerationRule", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteCodeGenerationRule")
    @WebMethod
    @ResponseWrapper(localName = "deleteCodeGenerationRuleResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteCodeGenerationRuleResponse")
    public boolean deleteCodeGenerationRule(
        @WebParam(name = "codeGenerationRuleDto", targetNamespace = "")
        com.docu.plugin.wsdl.CodeGenerationRuleDTO codeGenerationRuleDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveBankAccountType", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveBankAccountType")
    @WebMethod
    @ResponseWrapper(localName = "saveBankAccountTypeResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveBankAccountTypeResponse")
    public boolean saveBankAccountType(
        @WebParam(name = "bankAccountTypeDto", targetNamespace = "")
        com.docu.plugin.wsdl.BankAccountTypeDTO bankAccountTypeDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteOrganizationDepartment", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteOrganizationDepartment")
    @WebMethod
    @ResponseWrapper(localName = "deleteOrganizationDepartmentResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteOrganizationDepartmentResponse")
    public boolean deleteOrganizationDepartment(
        @WebParam(name = "organizationDepartmentDto", targetNamespace = "")
        com.docu.plugin.wsdl.OrganizationDepartmentDTO organizationDepartmentDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteHolidayType", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteHolidayType")
    @WebMethod
    @ResponseWrapper(localName = "deleteHolidayTypeResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteHolidayTypeResponse")
    public boolean deleteHolidayType(
        @WebParam(name = "holidayTypeDto", targetNamespace = "")
        com.docu.plugin.wsdl.HolidayTypeDTO holidayTypeDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveApplicationUser", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveApplicationUser")
    @WebMethod
    @ResponseWrapper(localName = "saveApplicationUserResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveApplicationUserResponse")
    public boolean saveApplicationUser(
        @WebParam(name = "applicationUserDto", targetNamespace = "")
        com.docu.plugin.wsdl.ApplicationUserDTO applicationUserDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveCountry", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveCountry")
    @WebMethod
    @ResponseWrapper(localName = "saveCountryResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveCountryResponse")
    public boolean saveCountry(
        @WebParam(name = "countryDto", targetNamespace = "")
        com.docu.plugin.wsdl.CountryDTO countryDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteMailNotificationInfo", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteMailNotificationInfo")
    @WebMethod
    @ResponseWrapper(localName = "deleteMailNotificationInfoResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteMailNotificationInfoResponse")
    public boolean deleteMailNotificationInfo(
        @WebParam(name = "mailNotificationInfoDto", targetNamespace = "")
        com.docu.plugin.wsdl.MailNotificationInfoDTO mailNotificationInfoDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveNationalityType", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveNationalityType")
    @WebMethod
    @ResponseWrapper(localName = "saveNationalityTypeResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveNationalityTypeResponse")
    public boolean saveNationalityType(
        @WebParam(name = "nationalityTypeDto", targetNamespace = "")
        com.docu.plugin.wsdl.NationalityTypeDTO nationalityTypeDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteUserPortletPreference", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteUserPortletPreference")
    @WebMethod
    @ResponseWrapper(localName = "deleteUserPortletPreferenceResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteUserPortletPreferenceResponse")
    public boolean deleteUserPortletPreference(
        @WebParam(name = "userPortletPreferenceDTO", targetNamespace = "")
        com.docu.plugin.wsdl.UserPortletPreferenceDTO userPortletPreferenceDTO
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveTaskStatus", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveTaskStatus")
    @WebMethod
    @ResponseWrapper(localName = "saveTaskStatusResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveTaskStatusResponse")
    public boolean saveTaskStatus(
        @WebParam(name = "taskStatusDto", targetNamespace = "")
        com.docu.plugin.wsdl.TaskStatusDTO taskStatusDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteUserPreference", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteUserPreference")
    @WebMethod
    @ResponseWrapper(localName = "deleteUserPreferenceResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteUserPreferenceResponse")
    public boolean deleteUserPreference(
        @WebParam(name = "userPreferenceDTO", targetNamespace = "")
        com.docu.plugin.wsdl.UserPreferenceDTO userPreferenceDTO
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteCountryLevelEntityOffice", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteCountryLevelEntityOffice")
    @WebMethod
    @ResponseWrapper(localName = "deleteCountryLevelEntityOfficeResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.DeleteCountryLevelEntityOfficeResponse")
    public boolean deleteCountryLevelEntityOffice(
        @WebParam(name = "countryLevelEntityOfficeDto", targetNamespace = "")
        com.docu.plugin.wsdl.CountryLevelEntityOfficeDTO countryLevelEntityOfficeDto
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saveFrequency", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveFrequency")
    @WebMethod
    @ResponseWrapper(localName = "saveFrequencyResponse", targetNamespace = "http://com.docu", className = "com.docu.plugin.wsdl.SaveFrequencyResponse")
    public boolean saveFrequency(
        @WebParam(name = "frequencyDto", targetNamespace = "")
        com.docu.plugin.wsdl.FrequencyDTO frequencyDto
    );
}
